name: stack
channels:
  - anaconda
  - defaults
dependencies:
  - asgiref=3.8.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - django=5.1.3
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.10.16
  - setuptools=75.8.0
  - sqlite=3.45.3
  - sqlparse=0.5.2
  - tk=8.6.14
  - typing_extensions=4.12.2
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - attrs==25.3.0
      - blobfile==3.0.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - distro==1.9.0
      - exceptiongroup==1.2.2
      - filelock==3.18.0
      - fire==0.7.0
      - fsspec==2025.3.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.29.3
      - idna==3.10
      - jinja2==3.1.6
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - llama-stack==0.1.9
      - llama-stack-client==0.1.9
      - lxml==5.3.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - numpy==2.2.4
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
